#Build Stage Start
FROM node:alpine as builder 
WORKDIR '/app'
COPY package.json .
RUN npm install
RUN npm install pm2 -g
COPY . .
RUN npm run build

EXPOSE 3001

CMD [ "pm2-runtime", "./build/server.js" ]